---
title: "Sergio Castrillo"
---

Reto | Citi Bike : Análisis del uso de Bicicletas de la ciudad de Nueva York


Duración: 2h


Objetivo:

Con el desarrollo del reto se integrarán todos los conocimientos adquiridos en éste y los módulos previos del diplomado, cumpliendo los siguientes objetivos:

Realizar un análisis de los datos para conocer su estructura y contenido, y así relacionarla con los requisitos del reto
Desarrollar funciones que nos permitan obtener datos de una manera eficiente
Crear, desplegar las aplicación web en la nube seleccionada y que nos permitan visualizar datos de acuerdo a los requerimientos.

Introducción:

Citi Bike es el proyecto de bicicletas compartidas más grande de Estados Unidos, con más de 20,000 bicicletas y alrededor de 1,300 estaciones alrededor de Manhattan, Brooklyn, Queens, the Bronx y  Jersey City.
Existe una base de datos con la información de los recorridos reales que realizan las personas, los científicos de datos pueden usar este dataset para construir dashboards que permitan visualizar esos recorridos, graficar el uso de bicicletas por hora, pintar en mapas las estaciones de bicicletas con más demanda por hora del día, entre otros.

Se tomará el mes de septiembre del 2021, recuperado del portal https://ride.citibikenyc.com/system-data.


Instrucciones:

Los siguientes pasos te guiarán en el proceso de desarrollo del reto para que logres completarlo con éxito:

**1.** Genera una un repositorio en Github con el nombre: reto-nombre-apellido. Crea un aplicación con RStudio tipo Markdown R Website con el nombre: mardown-menu. En la aplicación crea 2 links para redireccionar  hacia cada uno de los proyectos del paso 2, 3. Despliega tu aplicación en Github usando Github Pages.

**2.** Crea un proyecto nuevo en firebase con el nombre: citybike-nombre-apellido. En RStudio crea una aplicación tipo Markdown R Website con el nombre: markdown-citibike, incluye Scripts en R para desplegar una muestra de 1000 registros del dataset. Subir código a Github y publicar en firebase.

**3.**Crea una aplicación en RStudio tipo Shiny Web Application, con nombre: shiny-citibike. Crear código en R para mostrar alguna funcionalidad de tu agrado, como: Número de recorridos por hora, Cantidad de usuarios por estación, algún gráfico,  análisis de tu interés, entre otros. Se requiere una funcionalidad simple solo para propósitos de desplegar correctamente en Heroku (con nombre: https://citibike-nombre-apellido.herokuapp.com/ ) y almacenar el código en Github. 

Formato de entrega de actividad: 

Para la entrega de tu solución al reto deberás subir en Canvas un archivo:

Documento en word con tu nombre, y la siguiente información:
URL del repositorio Github y de la página en Github del punto 1.
URL del repositorio Github y de la página en firebase del punto 2:  https://citybike-nombre-apellido.web.app
URL del repositorio Github y de la página en heroku:  https://citybike-nombre-apellido.herokuapp.com


Evaluación: 

Tu reporte será evaluado con base al cumplimiento de los requerimientos y a su contenido, pero también por su presentación. La fecha límite de envío del archivo de tu reporte estará establecida en la plataforma Canvas.
